### ISSUE TITLE
[back-up-firestore-to-storage] Backup not working and not appear in storage

### ISSUE THREAD

**Issue by mattyx97** [htsuruo/firebase-extensions#13]
Hi I have installed this extension but ,backup not working and not appear in storage.
I just installed it and schedule everyday at 00:00 but It seems not working

**Comment by htsuruo** [comment]
@mattyx97 

Hi, thanks for your report.
Could you let me know about your detail information?

**1. What did you set for the configuration parameters?** 

```yaml
Cloud Storage bucket:
Cloud Storage prefix path:
Firestore collection ids:
The frequency at which you want to execute the backup:
The time zone in which the schedule will run (Defaults to UTC):
Cloud Functions location:
```

**2. What types of error logs are output in the Cloud Logging?** 

Procedure: 
1. Visit **Firebase Cloud Functions** page in Firebase GUI Console.
2. Click the more icon located on the right of `firebase-ext-back-up-firestore-to-storage-backupTransaction`
3. Select `View logs`

<img width="183" alt="image" src="https://github.com/HTsuruo/firebase-extensions/assets/12729025/0864acb1-4409-49b5-a9a4-16aae57998bb">

Thanks.
