### ISSUE TITLE
[trigger-github-issues-from-crashlytics] Error serializing return value

### ISSUE THREAD

**Issue by a-shine** [htsuruo/firebase-extensions#21]
Hi @htsuruo,

Thanks for your work on the Firebase extension!

After going through the installation and setting up the GitHub PAT in Secret Manager as instructed, I am facing the following issue in the cloud function responsible for creating the Issue `ext-trigger-github-issues-from-crashlytics-createFatalIssue`. Any help getting this to work would be greatly appreciated. As far as I know, all the other configurations are working; i.e., the function is triggered when a Crashlytics event occurs, and authentication to GitHub should be working.

Could this be happening due to a change in the event payload since the extension was first published?

Below is the logged `textPayload`:
```
Error serializing return value: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type function ([Function (anonymous)])
```

**Comment by htsuruo** [comment]
Thanks your report.
I'll check the issue.

**Comment by htsuruo** [comment]
@a-shine 

Thanks your report.
I'll check the issue.

**Comment by htsuruo** [comment]
Note: Here is `eventTrigegrs` shema at 2025.05.06.

https://raw.githubusercontent.com/firebase/firebase-tools/master/schema/extension-yaml.json

```yaml
{
  "type": "object",
  "description": "A function triggered by a background event",
  "properties": {
    "eventType": {
      "type": "string",
      "description": "The type of background event to trigger on. See https://firebase.google.com/docs/extensions/publishers/functions#supported for a full list."
    },
    "resource": {
      "type": "string",
      "description": "The name or pattern of the resource to trigger on"
    },
    "eventFilters": {
      "type": "string",
      "description": "Filters that further limit the events to listen to."
    },
    "channel": {
      "type": "string",
      "description": "The name of the channel associated with the trigger in projects/{project}/locations/{location}/channels/{channel} format. If you omit this property, the function will listen for events on the project's default channel."
    },
    "triggerRegion": {
      "type": "string",
      "description": "The trigger will only receive events originating in this region. It can be the same region as the function, a different region or multi-region, or the global region. If not provided, defaults to the same region as the function."
    }
  },
  "required": ["eventType"]
}

```

追記: これは単純にVS Codeのスキーマ（開発段階での）が間違っているという話（本来はおそらくstringではなく`object`が正しい）だと思うので、Editor上はエラーがでてしまうが、extensions.yamlの仕様としては間違っているわけではなさそう。
https://github.com/firebase/firebase-tools/pull/5984
